# -*- coding: utf-8 -*-
# pylint: skip-file
# Generated by Django 1.11.29 on 2020-09-11 19:19

from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_kit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleditem',
            old_name='identifier',
            new_name='respondent',
        ),
        migrations.RemoveField(
            model_name='scheduleditem',
            name='item_end',
        ),
        migrations.RemoveField(
            model_name='scheduleditem',
            name='item_start',
        ),
        migrations.AddField(
            model_name='scheduleditem',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleditem',
            name='end_time',
            field=models.TimeField(default=datetime.time(19, 19, 41, 116664)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleditem',
            name='start_time',
            field=models.TimeField(default=datetime.time(19, 19, 46, 748844)),
            preserve_default=False,
        ),
    ]
